Update criarteste

diff --git a/Modules/criarteste b/Modules/criarteste
--- a/Modules/criarteste
+++ b/Modules/criarteste
@@ -3,47 +3,47 @@ IP=$(cat /etc/IP)
 if [ ! -d /etc/VPSManager/userteste ]; then
 mkdir /etc/VPSManager/userteste
 fi
-tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "Criar usuario teste" ; tput sgr0
+tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-15s\n' "CREATE TEST USER" ; tput sgr0
 echo ""
-[ "$(ls -A /etc/VPSManager/userteste)" ] && echo -e "\033[1;32mTeste Ativo!\033[1;37m" || echo -e "\033[1;31mNenhum test ativo!\033[0m"
+[ "$(ls -A /etc/VPSManager/userteste)" ] && echo -e "\033[1;32mACTIVE TEST!\033[1;37m" || echo -e "\033[1;31mNO ACTIVE TESTS!\033[0m"
 echo ""
 for testeson in $(ls /etc/VPSManager/userteste |sort |sed 's/.sh//g')
 do
 echo "$testeson"
 done
 echo ""
-echo -ne "\033[1;32mNome do usuario\033[1;37m: "; read nome
+echo -ne "\033[1;32mUSER NAME\033[1;37m: "; read nome
 if [[ -z $nome ]]
 then
 echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Nome vazio ou invalido." ; echo "" ; tput sgr0
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID NAME." ; echo "" ; tput sgr0
 	exit 1
 fi
 awk -F : ' { print $1 }' /etc/passwd > /tmp/users 
 if grep -Fxq "$nome" /tmp/users
 then
-	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Este usuário já existe." ; echo "" ; tput sgr0
+	tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "THIS USER ALREADY EXISTS." ; echo "" ; tput sgr0
 	exit 1
 fi
-echo -ne "\033[1;32mSenha\033[1;37m: "; read pass
+echo -ne "\033[1;32mPASSWORD\033[1;37m: "; read pass
 if [[ -z $pass ]]
 then
 echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Senha vazia ou invalida." ; echo "" ; tput sgr0
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID PASSWORD." ; echo "" ; tput sgr0
 	exit 1
 fi
-echo -ne "\033[1;32mLimite\033[1;37m: "; read limit
+echo -ne "\033[1;32mLIMIT\033[1;37m: "; read limit
 if [[ -z $limit ]]
 then
 echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Limite vazio ou invalido." ; echo "" ; tput sgr0
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID LIMIT." ; echo "" ; tput sgr0
 	exit 1
 fi
-echo -ne "\033[1;32mMinutos \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
+echo -ne "\033[1;32mMINUTES \033[1;33m(\033[1;31mEx: \033[1;37m60\033[1;33m)\033[1;37m: "; read u_temp
 if [[ -z $limit ]]
 then
 echo ""
-tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "Limite vazio ou invalido." ; echo "" ; tput sgr0
+tput setaf 7 ; tput setab 1 ; tput bold ; echo "" ; echo "EMPTY OR INVALID LIMIT." ; echo "" ; tput sgr0
 	exit 1
 fi
 useradd -M -s /bin/false $nome
@@ -63,11 +63,11 @@ clear
 echo -e "\E[44;1;37m     Usuario Teste Criado     \E[0m"
 echo ""
 echo -e "\033[1;32mIP:\033[1;37m $IP"
-echo -e "\033[1;32mUsuario:\033[1;37m $nome"
-echo -e "\033[1;32mSenha:\033[1;37m $pass"
-echo -e "\033[1;32mLimite:\033[1;37m $limit"
-echo -e "\033[1;32mValidade:\033[1;37m $u_temp Minutos"
+echo -e "\033[1;32mUSERNAME:\033[1;37m $nome"
+echo -e "\033[1;32mPASSWORD:\033[1;37m $pass"
+echo -e "\033[1;32mLIMIT:\033[1;37m $limit"
+echo -e "\033[1;32mEXPIRY:\033[1;37m $u_temp Minutos"
 echo ""
-echo -e "\033[1;33mApos o tempo definido o usuario"
-echo -e "\033[1;32m$nome \033[1;33msera desconectado e deletado.\033[0m"
+echo -e "\033[1;33mAFTER THE TIME DEFINED THE USER"
+echo -e "\033[1;32m$nome \033[1;33mIT WILL BE DISCONNECTED AND DELETED.\033[0m"
 exit
